window.noname_update = {
	version: "1.4.0",
	update: "1.4.0",
	changeLog: [
			"功能",
			"新增排行榜功能",
			"角色包新增破晓",
			"lib.filter目标选择预设增加teammate、opponent、ourSide",
			"chooseToDiscard事件可支持设置loseTo参数，用于设置弃牌去向",
			"增加扩展自动导入功能，代码来源libnoname/noname/pull/2522",
			"增加玩家函数chooseButtonTarget,代码来源mengxinzxz",
			"在事件addToExpansion中增加时机addToExpansion,用于部分技能检测",
			"在事件addToExpansion中增加时机addToExpansion,用于部分技能检测",
			"新增，标记content和markcount支持'gaiPai'参数，标记contenti支持'iChuXiaoGuo'参数，自动处理盖牌显示逻辑；标记新增show参数，用以标记展示盖牌。",
			"增加增加/减少士气函数add/removeShiQi",
			"增加统计红蓝灯的函数countHong/Lan",
			"增加玩家函数countGaiPai，getGaiPai",
			"增加玩家函数hasGaiPai",
			"新增玩家函数countZhiLiao、countEmptyZhiLiao",
			"增加玩家函数addJiChuXiaoGuo、getJiChuXiaoGuo、countJiChuXiaoGuo,完善函数hasJiChuXiaoGuo",
			"增加玩家函数addGaiPai,参数cards，boolean:是否是展示盖牌默认false，source",
			"给移除基础效果和获得基础效果增加resulti返回值，xiaoGuo和card参数",

			"ai",
			"优化怪弓原初之弓圣光爆裂ai",
			"优化神官神圣契约操作及ai,使用新函数chooseButtonTarget",
			"优化女仆长关于影的ai",
			"修复冒险家偷天换日ai可在对面没红下发动一选项",

			"优化",
			"优化圣弓流行圣弹发动提示",
			"使用chooseButtonTarget优化圣光爆裂二选项、强予愿行、末日预言",
			"优化get.xiBie函数代码",
			"优化添加基础效果和盖牌日志",
			"优化addToExpansion日志和giveAuto动画，单机下改为不显示牌面",
			"优化捣蛋萝莉tricky基础效果显示描述",
			"优化捣蛋萝莉叛逆之墙，增加放置的圣盾的日志",
			"优化禁忌秘法技能描述",

			"bug",
			"调整三版/十周年吟游诗人沉沦协奏曲、异教徒预言翻面优先级",
			"修复传教士传道执行的弃牌（魔弹）可被暴食少女获取",
			"修复原初之弓圣光爆裂一选项无合法目标时无法发动",
			"修复嫉妒少女醋意羞心发动时提示错误",
			"修复异教徒天雷劫火和地裂波涛可以选择队友",

	],
	files: [

	],
};
